### ISSUE TITLE
Cannot save changes on file with CTRL+S

### ISSUE THREAD

**Issue by asarialtun** [hwclass/ziya#58]
## Version Number
Ziya: 1.1.8
Node:  6.9.4
npm: 3.10.10
OS: Windows 10 (1607)
Browser: Mozilla Firefox 50.1.0
## Test Case
Saving changes in a file
## Steps to Reproduce
1. Open a text file from file tree.
2. Make some changes.
3. Press CTRL+S to save.
4. Check the file contents.
## Expected Behavior
The changes must be visible in the file
## Actual Behavior
The file is not changed and it is in original state.

**Comment by atakangktepe** [comment]
Hi @asarialtun it's fixed in #59. @hwclass can you close this issue? 

Thanks :)
